# World Happiness Report 2016

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
import folium

- https://www.weforum.org/agenda/2016/07/greenest-happiest-country-in-the-world/
- https://medium.com/age-of-awareness/ecological-footprint-earth-overshoot-day-and-the-happy-planet-index-8ff5fc19af06

## Chargement des données

#### Les différents types de fichiers:
- Happy Planet Index: http://happyplanetindex.org/
- Kaggle - World Happiness 2016: https://www.kaggle.com/unsdsn/world-happiness/version/1

In [2]:
WH2015 = pd.read_csv('/Users/Johanna/Documents/SIMPLON/CHEF DOEUVRE/SOURCE/world-happiness/world-happiness-report-2015.csv')
WH2016 = pd.read_csv('/Users/Johanna/Documents/SIMPLON/CHEF DOEUVRE/SOURCE/world-happiness/world-happiness-report-2016.csv')
WH2017 = pd.read_csv('/Users/Johanna/Documents/SIMPLON/CHEF DOEUVRE/SOURCE/world-happiness/world-happiness-report-2017.csv')
WH2018 = pd.read_csv('/Users/Johanna/Documents/SIMPLON/CHEF DOEUVRE/SOURCE/world-happiness/world-happiness-report-2018.csv')

#### Kaggle - World Happiness 2015

In [3]:
WH2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

#### Kaggle - World Happiness 2016

In [4]:
WH2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

#### Kaggle - World Happiness 2017

In [5]:
WH2017.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

#### Kaggle - World Happiness 2018

In [6]:
WH2018.head()

,Rank,Country,Score,GDP_Per_Capita,Social_Support,Healthy_Life_Expectancy,Freedom_To_Make_Life_Choices,Generosity,Perceptions_Of_Corruption,Residual
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.192,0.393,2.988
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340,2.723
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408,2.779
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138,2.564
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357,2.675

## Analyse des données

- Supprimer les données superflues et les valeurs aberrantes
- Ajouter les valeurs manquantes
- Adapter les données à une structure standard
- Masquer les données privées ou sensibles

#### Descriptif / Informations des colonnes
- WH2015: World Happiness 2015

In [7]:
WH2015.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,79.493671,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,45.754363,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.250000,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,79.500000,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,118.750000,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,158.000000,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [8]:
WH2015.dtypes

Country                           object
Region                            object
Happiness Rank                     int64
Happiness Score                  float64
Standard Error                   float64
Economy (GDP per Capita)         float64
Family                           float64
Health (Life Expectancy)         float64
Freedom                          float64
Trust (Government Corruption)    float64
Generosity                       float64
Dystopia Residual                float64
dtype: object

In [9]:
# REORGANISATION DE L'ORDRE DES COLONNES
WH2017 = WH2017[['Country', 'Happiness.Rank', 'Happiness.Score', 'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.', 'Freedom', 'Trust..Government.Corruption.', 'Generosity', 'Dystopia.Residual'  ]]
WH2017

,Country,Happiness.Rank,Happiness.Score,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Trust..Government.Corruption.,Generosity,Dystopia.Residual
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182
...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061
151,Syria,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574
152,Tanzania,153,3.349,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130
153,Burundi,154,2.905,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024
154,Central African Republic,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005

In [10]:
WH2018.head()
WH2018 = WH2018[['Country', 'Rank', 'Score', 'GDP_Per_Capita', 'Social_Support', 'Healthy_Life_Expectancy', 'Freedom_To_Make_Life_Choices', 'Perceptions_Of_Corruption', 'Generosity', 'Residual'  ]]
WH2018

,Country,Rank,Score,GDP_Per_Capita,Social_Support,Healthy_Life_Expectancy,Freedom_To_Make_Life_Choices,Perceptions_Of_Corruption,Generosity,Residual
0,Finland,1,7.632,1.305,1.592,0.874,0.681,0.393,0.192,2.988
1,Norway,2,7.594,1.456,1.582,0.861,0.686,0.340,0.286,2.723
2,Denmark,3,7.555,1.351,1.590,0.868,0.683,0.408,0.284,2.779
3,Iceland,4,7.495,1.343,1.644,0.914,0.677,0.138,0.353,2.564
4,Switzerland,5,7.487,1.420,1.549,0.927,0.660,0.357,0.256,2.675
...,...,...,...,...,...,...,...,...,...,...
151,Yemen,152,3.355,0.442,1.073,0.343,0.244,0.064,0.083,1.170
152,Tanzania,153,3.303,0.455,0.991,0.381,0.481,0.097,0.270,0.725
153,South Sudan,154,3.254,0.337,0.608,0.177,0.112,0.106,0.224,1.796
154,Central African Republic,155,3.083,0.024,0.000,0.010,0.305,0.038,0.218,2.526
155,Burundi,156,2.905,0.091,0.627,0.145,0.065,0.076,0.149,1.828

In [11]:
# RENAME COLUMN DATAFRAMES:
WH2015.rename(columns={'Happiness Rank':'Happiness_Rank',
                       'Happiness Score':'Happiness_Score',
                       'Economy (GDP per Capita)':'GDP',
                       'Health (Life Expectancy)':'Health',
                       'Trust (Government Corruption)': 'Trust',
                       'Dystopia Residual': 'Dystopia_Residual'
                      }, inplace=True)
WH2015

,Country,Region,Happiness_Rank,Happiness_Score,Standard Error,GDP,Family,Health,Freedom,Trust,Generosity,Dystopia_Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [12]:
WH2016.rename(columns={'Happiness Rank':'Happiness_Rank',
                       'Happiness Score':'Happiness_Score',
                       'Economy (GDP per Capita)':'GDP',
                       'Health (Life Expectancy)':'Health',
                       'Trust (Government Corruption)': 'Trust',
                       'Dystopia Residual': 'Dystopia_Residual'
                      }, inplace=True)
WH2016

,Country,Region,Happiness_Rank,Happiness_Score,Lower Confidence Interval,Upper Confidence Interval,GDP,Family,Health,Freedom,Trust,Generosity,Dystopia_Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [13]:
WH2017.rename(columns={'Happiness.Rank':'Happiness_Rank',
                       'Happiness.Score':'Happiness_Score',
                       'Economy..GDP.per.Capita.':'GDP',
                       'Health..Life.Expectancy.':'Health',
                       'Trust..Government.Corruption.': 'Trust',
                       'Dystopia.Residual': 'Dystopia_Residual'
                      }, inplace=True)
WH2017

,Country,Happiness_Rank,Happiness_Score,GDP,Family,Health,Freedom,Trust,Generosity,Dystopia_Residual
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182
...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061
151,Syria,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574
152,Tanzania,153,3.349,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130
153,Burundi,154,2.905,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024
154,Central African Republic,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005

In [14]:
WH2018

,Country,Rank,Score,GDP_Per_Capita,Social_Support,Healthy_Life_Expectancy,Freedom_To_Make_Life_Choices,Perceptions_Of_Corruption,Generosity,Residual
0,Finland,1,7.632,1.305,1.592,0.874,0.681,0.393,0.192,2.988
1,Norway,2,7.594,1.456,1.582,0.861,0.686,0.340,0.286,2.723
2,Denmark,3,7.555,1.351,1.590,0.868,0.683,0.408,0.284,2.779
3,Iceland,4,7.495,1.343,1.644,0.914,0.677,0.138,0.353,2.564
4,Switzerland,5,7.487,1.420,1.549,0.927,0.660,0.357,0.256,2.675
...,...,...,...,...,...,...,...,...,...,...
151,Yemen,152,3.355,0.442,1.073,0.343,0.244,0.064,0.083,1.170
152,Tanzania,153,3.303,0.455,0.991,0.381,0.481,0.097,0.270,0.725
153,South Sudan,154,3.254,0.337,0.608,0.177,0.112,0.106,0.224,1.796
154,Central African Republic,155,3.083,0.024,0.000,0.010,0.305,0.038,0.218,2.526
155,Burundi,156,2.905,0.091,0.627,0.145,0.065,0.076,0.149,1.828

In [15]:
WH2018.rename(columns={'Rank':'Happiness_Rank',
                       'Score':'Happiness_Score',
                       'GDP_Per_Capita':'GDP',
                       'Social_Support': 'Family',
                       'Healthy_Life_Expectancy':'Health',
                       'Freedom_To_Make_Life_Choices':'Freedom',
                       'Perceptions_Of_Corruption': 'Trust',
                       'Residual': 'Dystopia_Residual'
                      }, inplace=True)
WH2018

,Country,Happiness_Rank,Happiness_Score,GDP,Family,Health,Freedom,Trust,Generosity,Dystopia_Residual
0,Finland,1,7.632,1.305,1.592,0.874,0.681,0.393,0.192,2.988
1,Norway,2,7.594,1.456,1.582,0.861,0.686,0.340,0.286,2.723
2,Denmark,3,7.555,1.351,1.590,0.868,0.683,0.408,0.284,2.779
3,Iceland,4,7.495,1.343,1.644,0.914,0.677,0.138,0.353,2.564
4,Switzerland,5,7.487,1.420,1.549,0.927,0.660,0.357,0.256,2.675
...,...,...,...,...,...,...,...,...,...,...
151,Yemen,152,3.355,0.442,1.073,0.343,0.244,0.064,0.083,1.170
152,Tanzania,153,3.303,0.455,0.991,0.381,0.481,0.097,0.270,0.725
153,South Sudan,154,3.254,0.337,0.608,0.177,0.112,0.106,0.224,1.796
154,Central African Republic,155,3.083,0.024,0.000,0.010,0.305,0.038,0.218,2.526
155,Burundi,156,2.905,0.091,0.627,0.145,0.065,0.076,0.149,1.828

In [16]:
# SUPPRIMER DES COLONNES:
WH2015 = WH2015.drop(['Region', 'Standard Error','GDP' ], axis = 1)
WH2016 = WH2016.drop(['Region','Lower Confidence Interval', 'Upper Confidence Interval', 'GDP',  ], axis = 1)
WH2017 = WH2017.drop(['GDP'], axis = 1)
WH2018 = WH2018.drop(['GDP'], axis = 1)

In [17]:
# NORMALISATION DES INFORMATIONS PAR COLONNES: Country
WH2015_country = WH2015["Country"].unique()
WH2016_country = WH2015["Country"].unique()
WH2017_country = WH2015["Country"].unique()
WH2018_country = WH2015["Country"].unique()

sorted(WH2015_country)
sorted(WH2016_country)
sorted(WH2017_country)
sorted(WH2018_country)

['Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 'Costa Rica',
 'Croatia',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Ethiopia',
 'Finland',
 'France',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guinea',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Cyprus',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestinian Territories',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Somaliland region',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [18]:
len(sorted(WH2016_country))

158

In [19]:
# COMPARE TWO LISTS AND RETURN MATCHES:
# SAME SAME
country_matches = set(WH2015_country) & set(WH2016_country) & set(WH2017_country) & set(WH2018_country)
country_matches = list(sorted(country_matches))
len(country_matches)

158

In [20]:
# ADD COLUMNS TO DATAFRAME: Years
WH2015['Years'] = 2015 
WH2016['Years'] = 2016
WH2017['Years'] = 2017
WH2018['Years'] = 2018
WH2015

,Country,Happiness_Rank,Happiness_Score,Family,Health,Freedom,Trust,Generosity,Dystopia_Residual,Years
0,Switzerland,1,7.587,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015
1,Iceland,2,7.561,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015
2,Denmark,3,7.527,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015
3,Norway,4,7.522,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015
4,Canada,5,7.427,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015
...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,154,3.465,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042,2015
154,Benin,155,3.340,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328,2015
155,Syria,156,3.006,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858,2015
156,Burundi,157,2.905,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302,2015
157,Togo,158,2.839,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726,2015

In [21]:
WH2015 = WH2015.reindex(columns = ['Country', 'Years', 'Happiness_Rank', 'Happiness_Score', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Dystopia_Residual'])
WH2016 = WH2016.reindex(columns = ['Country', 'Years', 'Happiness_Rank', 'Happiness_Score', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Dystopia_Residual'])
WH2017 = WH2017.reindex(columns = ['Country', 'Years', 'Happiness_Rank', 'Happiness_Score', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Dystopia_Residual'])
WH2018 = WH2018.reindex(columns = ['Country', 'Years', 'Happiness_Rank', 'Happiness_Score', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Dystopia_Residual'])

In [22]:
# https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
WH = [WH2015, WH2016, WH2017, WH2018]
WH_all = pd.concat(WH)

In [23]:
WH_all

,Country,Years,Happiness_Rank,Happiness_Score,Family,Health,Freedom,Trust,Generosity,Dystopia_Residual
0,Switzerland,2015,1,7.587,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,2015,2,7.561,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,2015,3,7.527,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,2015,4,7.522,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,2015,5,7.427,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...
151,Yemen,2018,152,3.355,1.07300,0.34300,0.24400,0.06400,0.08300,1.17000
152,Tanzania,2018,153,3.303,0.99100,0.38100,0.48100,0.09700,0.27000,0.72500
153,South Sudan,2018,154,3.254,0.60800,0.17700,0.11200,0.10600,0.22400,1.79600
154,Central African Republic,2018,155,3.083,0.00000,0.01000,0.30500,0.03800,0.21800,2.52600
155,Burundi,2018,156,2.905,0.62700,0.14500,0.06500,0.07600,0.14900,1.82800

In [24]:
WH_all.dtypes

Country               object
Years                  int64
Happiness_Rank         int64
Happiness_Score      float64
Family               float64
Health               float64
Freedom              float64
Trust                float64
Generosity           float64
Dystopia_Residual    float64
dtype: object

In [25]:
WH_all.to_csv('WH_all.csv')

In [26]:
# connecter à MySQL  
# mysql+pymysql://<username>:<password>@<host>/<dbname>[?<options>]
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:password.?19@127.0.0.1/footprint?host=127.0.0.1?port=3306") 
conn = engine.connect() 
print('connected')

connected

In [27]:
WH_all

,Country,Years,Happiness_Rank,Happiness_Score,Family,Health,Freedom,Trust,Generosity,Dystopia_Residual
0,Switzerland,2015,1,7.587,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,2015,2,7.561,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,2015,3,7.527,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,2015,4,7.522,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,2015,5,7.427,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...
151,Yemen,2018,152,3.355,1.07300,0.34300,0.24400,0.06400,0.08300,1.17000
152,Tanzania,2018,153,3.303,0.99100,0.38100,0.48100,0.09700,0.27000,0.72500
153,South Sudan,2018,154,3.254,0.60800,0.17700,0.11200,0.10600,0.22400,1.79600
154,Central African Republic,2018,155,3.083,0.00000,0.01000,0.30500,0.03800,0.21800,2.52600
155,Burundi,2018,156,2.905,0.62700,0.14500,0.06500,0.07600,0.14900,1.82800

In [28]:
CREATE TABLE IF NOT EXISTS WH (
	Country VARCHAR (48),
    Years YEARS (4),
    Happiness_Rank INT,
    Happiness_Score FLOAT,
    Family FLOAT,
    Health FLOAT,
    Freedom FLOAT,
    Trust FLOAT,
    Generosity FLOAT,
    Dystopia_Residual FLOAT,
    PRIMARY KEY AUTO_INCREMENT(Country, Years)
);

SyntaxError: invalid syntax (<ipython-input-28-481d603ab3bb>, line 1)

In [30]:
ALTER TABLE WH 
	MODIFY Country VARCHAR (48),
    MODIFY Years YEAR (4),
    MODIFY Happiness_Rank INT,
    MODIFY Happiness_Score FLOAT,
    MODIFY Family FLOAT,
    MODIFY Health FLOAT,
    MODIFY Freedom FLOAT,
    MODIFY Trust FLOAT,
    MODIFY Generosity FLOAT,
    MODIFY Dystopia_Residual FLOAT,
    ADD PRIMARY KEY (Country, Years)
;

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [31]:
WH_all.to_sql('WH', conn, if_exists='replace', index = False)

In [32]:
table_WH_1 = 'CREATE TABLE IF NOT EXISTS WH (Country VARCHAR (48), Years YEAR (4), Happiness_Rank INT, Happiness_Score FLOAT, Family FLOAT, Health FLOAT, Freedom FLOAT, Trust FLOAT, Generosity FLOAT, Dystopia_Residual FLOAT, PRIMARY KEY AUTO_INCREMENT(Country, years));'

In [33]:
table_WH = 'ALTER TABLE WH MODIFY Country VARCHAR (48), MODIFY Years YEAR (4), MODIFY Happiness_Rank INT, MODIFY Happiness_Score FLOAT, MODIFY Family FLOAT, MODIFY Health FLOAT, MODIFY Freedom FLOAT, MODIFY Trust FLOAT, MODIFY Generosity FLOAT, MODIFY Dystopia_Residual FLOAT, ADD PRIMARY KEY (Country, Years);'

In [34]:
import pymysql
import pymysql.cursors

In [35]:
# create connection
connection = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='password.?19')

print('Connected to DB: {}'.format(connection))

Connected to DB: <pymysql.connections.Connection object at 0x11d98f320>

In [36]:
# Create cursor and execute Load SQL
cursor = connection.cursor()

In [37]:
# Connect DB
cursor.execute('USE footprint;')

0

In [38]:
# importer un DF dans une table
WH_all.to_sql('WH', conn, if_exists='replace', index = False)

In [39]:
cursor.execute('ALTER TABLE WH MODIFY Country VARCHAR (48), MODIFY Years YEAR (4), MODIFY Happiness_Rank INT, MODIFY Happiness_Score FLOAT, MODIFY Family FLOAT, MODIFY Health FLOAT, MODIFY Freedom FLOAT, MODIFY Trust FLOAT, MODIFY Generosity FLOAT, MODIFY Dystopia_Residual FLOAT, ADD PRIMARY KEY (Country, Years);')

626

In [40]:
# Execute Query
cursor.execute("SELECT * from WH")

# Fetch the records
result = cursor.fetchall()

for i in result:
    print(i)

# Close the connection
connection.close()

('Afghanistan', 2015, 153, 3.575, 0.30285, 0.30335, 0.23414, 0.09719, 0.3651, 1.9521)
('Afghanistan', 2016, 154, 3.36, 0.11037, 0.17344, 0.1643, 0.07112, 0.31268, 2.14558)
('Afghanistan', 2017, 141, 3.794, 0.581543, 0.180747, 0.10618, 0.0611578, 0.311871, 2.1508)
('Afghanistan', 2018, 145, 3.632, 0.537, 0.255, 0.085, 0.036, 0.191, 2.232)
('Albania', 2015, 95, 4.959, 0.80434, 0.81325, 0.35733, 0.06413, 0.14272, 1.89894)
('Albania', 2016, 109, 4.655, 0.50163, 0.73007, 0.31866, 0.05301, 0.1684, 1.92816)
('Albania', 2017, 109, 4.644, 0.803685, 0.73116, 0.381499, 0.0398642, 0.201313, 1.49044)
('Albania', 2018, 112, 4.586, 0.817, 0.79, 0.419, 0.032, 0.149, 1.495)
('Algeria', 2015, 68, 5.605, 1.07772, 0.61766, 0.28579, 0.17383, 0.07822, 2.43209)
('Algeria', 2016, 38, 6.355, 0.83309, 0.61804, 0.21006, 0.16157, 0.07044, 3.40904)
('Algeria', 2017, 53, 5.872, 1.14622, 0.617585, 0.233336, 0.146096, 0.0694366, 2.5676)
('Algeria', 2018, 84, 5.295, 1.154, 0.687, 0.077, 0.135, 0.055, 2.343)
('Angola', 2015, 137, 4.033, 0.8604, 0.16683, 0.10384, 0.07122, 0.12344, 1.94939)
('Angola', 2016, 141, 3.866, 0.66366, 0.04991, 0.00589, 0.08434, 0.12071, 2.09459)
('Angola', 2017, 140, 3.795, 1.10441, 0.0498687, 0.0, 0.0697203, 0.0979265, 1.61448)
('Angola', 2018, 142, 3.795, 1.125, 0.269, 0.0, 0.061, 0.079, 1.592)
('Argentina', 2015, 30, 6.574, 1.24823, 0.78723, 0.44974, 0.08484, 0.11451, 2.836)
('Argentina', 2016, 26, 6.65, 1.06612, 0.69711, 0.42284, 0.07296, 0.10989, 3.12985)
('Argentina', 2017, 24, 6.599, 1.44045, 0.695137, 0.494519, 0.0597399, 0.109457, 2.61401)
('Argentina', 2018, 29, 6.388, 1.468, 0.744, 0.57, 0.054, 0.062, 2.471)
('Armenia', 2015, 127, 4.35, 0.77711, 0.7299, 0.19847, 0.039, 0.07855, 1.75873)
('Armenia', 2016, 121, 4.36, 0.62477, 0.64083, 0.14037, 0.03616, 0.07793, 1.97864)
('Armenia', 2017, 121, 4.376, 1.00748, 0.637524, 0.198303, 0.0266744, 0.0834881, 1.5215)
('Armenia', 2018, 129, 4.321, 0.99, 0.666, 0.26, 0.028, 0.077, 1.512)
('Australia', 2015, 10, 7.284, 1.30923, 0.93156, 0.65124, 0.35637, 0.43562, 2.26646)
('Australia', 2016, 9, 7.313, 1.10476, 0.8512, 0.56837, 0.32331, 0.47407, 2.5465)
('Australia', 2017, 10, 7.284, 1.51004, 0.843887, 0.601607, 0.301184, 0.477699, 2.06521)
('Australia', 2018, 10, 7.272, 1.573, 0.91, 0.647, 0.302, 0.361, 2.441)
('Austria', 2015, 13, 7.2, 1.29704, 0.89042, 0.62433, 0.18676, 0.33088, 2.5332)
('Austria', 2016, 12, 7.119, 1.08383, 0.80565, 0.54355, 0.21348, 0.32865, 2.69343)
('Austria', 2017, 13, 7.006, 1.45994, 0.815328, 0.567766, 0.22106, 0.316472, 2.13851)
('Austria', 2018, 12, 7.139, 1.504, 0.891, 0.617, 0.224, 0.242, 2.544)
('Azerbaijan', 2015, 80, 5.212, 0.93793, 0.64045, 0.3703, 0.16065, 0.07799, 2.00073)
('Azerbaijan', 2016, 81, 5.291, 0.76042, 0.54504, 0.35327, 0.17914, 0.0564, 2.2735)
('Azerbaijan', 2017, 85, 5.234, 1.1524, 0.540776, 0.398156, 0.180988, 0.0452693, 1.76248)
('Azerbaijan', 2018, 87, 5.201, 1.161, 0.603, 0.43, 0.176, 0.031, 1.952)
('Bahrain', 2015, 49, 5.96, 1.21624, 0.74716, 0.45492, 0.306, 0.17362, 1.73797)
('Bahrain', 2016, 42, 6.218, 0.94397, 0.65696, 0.47375, 0.25772, 0.17147, 2.27405)
('Bahrain', 2017, 41, 6.087, 1.32311, 0.653133, 0.536747, 0.257042, 0.172668, 1.65615)
('Bahrain', 2018, 43, 6.105, 1.366, 0.698, 0.594, 0.123, 0.243, 1.866)
('Bangladesh', 2015, 109, 4.694, 0.43106, 0.60164, 0.4082, 0.12569, 0.21222, 2.51767)
('Bangladesh', 2016, 110, 4.643, 0.24749, 0.52989, 0.39778, 0.12583, 0.19132, 2.60904)
('Bangladesh', 2017, 110, 4.608, 0.735132, 0.533241, 0.478357, 0.123718, 0.172255, 1.97874)
('Bangladesh', 2018, 115, 4.5, 0.85, 0.579, 0.58, 0.144, 0.153, 1.806)
('Belarus', 2015, 59, 5.813, 1.23289, 0.73608, 0.37938, 0.1909, 0.11046, 2.1309)
('Belarus', 2016, 61, 5.802, 1.04993, 0.63104, 0.29091, 0.17457, 0.13942, 2.38582)
('Belarus', 2017, 67, 5.569, 1.44495, 0.637714, 0.2954, 0.156314, 0.155138, 1.72323)
('Belarus', 2018, 73, 5.483, 1.498, 0.7, 0.307, 0.154, 0.101, 1.838)
('Belgium', 2015, 19, 6.937, 1.28566, 0.89667, 0.5845, 0.2254, 0.2225, 2.41484)
('Belgium', 2016, 18, 6.929, 1.05249, 0.81959, 0.51354, 0.26248, 0.2424, 2.61355)
('Belgium', 2017, 17, 6.891, 1.46231, 0.818092, 0.539771, 0.251343, 0.231503, 2.12421)
('Belgium', 2018, 16, 6.927, 1.483, 0.894, 0.583, 0.24, 0.188, 2.455)
('Belize', 2016, 52, 5.956, 0.68655, 0.45569, 0.51231, 0.10771, 0.23684, 3.08039)
('Belize', 2017, 50, 5.956, 1.08142, 0.450192, 0.547509, 0.0965811, 0.240016, 2.63196)
('Belize', 2018, 49, 5.956, 1.101, 0.474, 0.593, 0.089, 0.183, 2.798)
('Benin', 2015, 155, 3.34, 0.35386, 0.3191, 0.4845, 0.0801, 0.1826, 1.63328)
('Benin', 2016, 153, 3.484, 0.10419, 0.21028, 0.39747, 0.06681, 0.2018, 2.10812)
('Benin', 2017, 143, 3.657, 0.4353, 0.20993, 0.425963, 0.060929, 0.207948, 1.88563)
('Benin', 2018, 136, 4.141, 0.372, 0.24, 0.44, 0.067, 0.163, 2.548)
('Bhutan', 2015, 79, 5.253, 1.10395, 0.57407, 0.53206, 0.15445, 0.47998, 1.63794)
('Bhutan', 2016, 84, 5.196, 0.90836, 0.49759, 0.46074, 0.1616, 0.48546, 1.82916)
('Bhutan', 2017, 97, 5.011, 1.34013, 0.495879, 0.501538, 0.17338, 0.474055, 1.14018)
('Bhutan', 2018, 97, 5.082, 1.335, 0.527, 0.541, 0.171, 0.364, 1.519)
('Bolivia', 2015, 51, 5.89, 0.97841, 0.5392, 0.57414, 0.088, 0.20536, 2.82334)
('Bolivia', 2016, 59, 5.822, 0.83779, 0.4697, 0.50961, 0.07746, 0.21698, 2.91635)
('Bolivia', 2017, 58, 5.823, 1.22762, 0.47363, 0.558733, 0.0604777, 0.225561, 2.44328)
('Bolivia', 2018, 62, 5.752, 1.223, 0.508, 0.606, 0.054, 0.141, 2.523)
('Bosnia and Herzegovina', 2015, 96, 4.949, 0.91916, 0.79081, 0.09245, 0.00227, 0.24808, 2.06367)
('Bosnia and Herzegovina', 2016, 87, 5.163, 0.64367, 0.70766, 0.09511, 0.0, 0.29889, 2.48406)
('Bosnia and Herzegovina', 2017, 90, 5.182, 1.06934, 0.705186, 0.204403, 0.0, 0.328867, 1.89217)
('Bosnia and Herzegovina', 2018, 93, 5.129, 1.078, 0.758, 0.28, 0.0, 0.216, 1.882)
('Botswana', 2015, 128, 4.332, 1.10464, 0.04776, 0.49495, 0.12474, 0.10461, 1.46181)
('Botswana', 2016, 137, 3.974, 0.89186, 0.34752, 0.44089, 0.10769, 0.12425, 0.96741)
('Botswana', 2017, 142, 3.766, 1.22155, 0.341756, 0.505196, 0.0985832, 0.0993484, 0.377914)
('Botswana', 2018, 146, 3.59, 1.174, 0.417, 0.557, 0.092, 0.042, 0.383)
('Brazil', 2015, 16, 6.983, 1.23287, 0.69702, 0.49049, 0.17521, 0.14574, 3.26001)
('Brazil', 2016, 17, 6.952, 1.03938, 0.61415, 0.40425, 0.14166, 0.15776, 3.50733)
('Brazil', 2017, 22, 6.635, 1.43131, 0.616552, 0.437454, 0.111093, 0.16235, 2.76927)
('Brazil', 2018, 28, 6.419, 1.474, 0.675, 0.493, 0.088, 0.11, 2.681)
('Bulgaria', 2015, 134, 4.218, 1.10614, 0.76649, 0.30587, 0.00872, 0.11921, 0.89991)
('Bulgaria', 2016, 129, 4.217, 0.92542, 0.67806, 0.21219, 0.00615, 0.12793, 1.15377)
('Bulgaria', 2017, 105, 4.714, 1.43438, 0.708218, 0.289232, 0.0110515, 0.113178, 0.996139)
('Bulgaria', 2018, 100, 4.933, 1.515, 0.712, 0.359, 0.009, 0.064, 1.229)
('Burkina Faso', 2015, 152, 3.587, 0.85188, 0.27125, 0.39493, 0.12832, 0.21747, 1.46494)
('Burkina Faso', 2016, 145, 3.739, 0.63054, 0.21297, 0.3337, 0.12533, 0.24353, 1.87319)
('Burkina Faso', 2017, 134, 4.032, 1.04328, 0.215844, 0.324368, 0.120328, 0.250865, 1.72721)
('Burkina Faso', 2018, 121, 4.424, 1.097, 0.254, 0.312, 0.128, 0.175, 2.272)
('Burundi', 2015, 157, 2.905, 0.41587, 0.22396, 0.1185, 0.10062, 0.19727, 1.83302)
('Burundi', 2016, 157, 2.905, 0.23442, 0.15747, 0.0432, 0.09419, 0.2029, 2.10404)
('Burundi', 2017, 154, 2.905, 0.629794, 0.151611, 0.0599008, 0.0841479, 0.204435, 1.68302)
('Burundi', 2018, 156, 2.905, 0.627, 0.145, 0.065, 0.076, 0.149, 1.828)
('Cambodia', 2015, 145, 3.819, 0.62736, 0.61114, 0.66246, 0.07247, 0.40359, 0.98195)
('Cambodia', 2016, 140, 3.907, 0.5375, 0.42494, 0.58852, 0.08092, 0.40339, 1.31573)
('Cambodia', 2017, 129, 4.168, 1.00624, 0.429783, 0.633376, 0.068106, 0.385923, 1.04294)
('Cambodia', 2018, 120, 4.433, 1.088, 0.457, 0.696, 0.065, 0.256, 1.387)
('Cameroon', 2015, 133, 4.252, 0.88767, 0.23402, 0.49309, 0.05786, 0.20618, 1.95071)
('Cameroon', 2016, 114, 4.513, 0.62542, 0.12698, 0.42736, 0.06126, 0.2268, 2.5198)
('Cameroon', 2017, 107, 4.695, 0.946018, 0.132892, 0.430389, 0.0513066, 0.236298, 2.33365)
('Cameroon', 2018, 99, 4.975, 0.891, 0.182, 0.454, 0.043, 0.183, 2.73)
('Canada', 2015, 5, 7.427, 1.32261, 0.90563, 0.63297, 0.32957, 0.45811, 2.45176)
('Canada', 2016, 6, 7.404, 1.0961, 0.8276, 0.5737, 0.31329, 0.44834, 2.70485)
('Canada', 2017, 7, 7.316, 1.48135, 0.834558, 0.611101, 0.287372, 0.43554, 2.18726)
('Canada', 2018, 7, 7.328, 1.532, 0.896, 0.653, 0.291, 0.321, 2.596)
('Central African Republic', 2015, 148, 3.678, 0.0, 0.06699, 0.48879, 0.08289, 0.23835, 2.7223)
('Central African Republic', 2017, 155, 2.693, 0.0, 0.0187727, 0.270842, 0.0565651, 0.280876, 2.066)
('Central African Republic', 2018, 155, 3.083, 0.0, 0.01, 0.305, 0.038, 0.218, 2.526)
('Chad', 2015, 149, 3.667, 0.76062, 0.1501, 0.23501, 0.05269, 0.18386, 1.94296)
('Chad', 2016, 144, 3.763, 0.63178, 0.03824, 0.12807, 0.04952, 0.18667, 2.30637)
('Chad', 2017, 137, 3.936, 0.953856, 0.0411347, 0.162342, 0.0535819, 0.216114, 2.07124)
('Chad', 2018, 131, 4.301, 0.907, 0.053, 0.189, 0.06, 0.181, 2.613)
('Chile', 2015, 27, 6.67, 1.12447, 0.85857, 0.44132, 0.12869, 0.33363, 2.67585)
('Chile', 2016, 24, 6.705, 0.90587, 0.81883, 0.37789, 0.11451, 0.31595, 2.95505)
('Chile', 2017, 20, 6.652, 1.28402, 0.81948, 0.376895, 0.082288, 0.326662, 2.50959)
('Chile', 2018, 25, 6.476, 1.331, 0.808, 0.431, 0.061, 0.197, 2.578)
('China', 2015, 84, 5.14, 0.94675, 0.81658, 0.51697, 0.02781, 0.08185, 1.8604)
('China', 2016, 83, 5.245, 0.79381, 0.73561, 0.44012, 0.02745, 0.04959, 2.17087)
('China', 2017, 79, 5.273, 1.16084, 0.741416, 0.472788, 0.0227943, 0.0288068, 1.76494)
('China', 2018, 86, 5.246, 1.142, 0.799, 0.597, 0.103, 0.029, 1.69)
('Colombia', 2015, 33, 6.477, 1.24018, 0.69077, 0.53466, 0.0512, 0.18401, 2.85737)
('Colombia', 2016, 31, 6.481, 1.02169, 0.59659, 0.44735, 0.05399, 0.15626, 3.17471)
('Colombia', 2017, 36, 6.357, 1.40218, 0.595028, 0.477487, 0.0466687, 0.149014, 2.61607)
('Colombia', 2018, 37, 6.26, 1.439, 0.635, 0.531, 0.039, 0.099, 2.596)
('Comoros', 2015, 140, 3.956, 0.79273, 0.36315, 0.22917, 0.199, 0.17441, 1.95812)
('Comoros', 2016, 138, 3.956, 0.60323, 0.29981, 0.15412, 0.18437, 0.1827, 2.25632)
('Congo (Brazzaville)', 2015, 139, 3.989, 0.6629, 0.31051, 0.41466, 0.11686, 0.12388, 1.68135)
('Congo (Brazzaville)', 2016, 127, 4.236, 0.47799, 0.28212, 0.37938, 0.09753, 0.12077, 2.10681)
('Congo (Brazzaville)', 2017, 124, 4.291, 0.832044, 0.289957, 0.435026, 0.0796181, 0.120852, 1.72414)
('Congo (Brazzaville)', 2018, 114, 4.559, 0.811, 0.343, 0.514, 0.077, 0.091, 2.118)
('Congo (Kinshasa)', 2015, 120, 4.517, 1.0012, 0.09806, 0.22605, 0.07625, 0.24834, 2.86712)
('Congo (Kinshasa)', 2016, 125, 4.272, 0.80676, 0.188, 0.15602, 0.06075, 0.25458, 2.74924)
('Congo (Kinshasa)', 2017, 126, 4.28, 1.22902, 0.191407, 0.235961, 0.0602414, 0.246456, 2.22496)
('Congo (Kinshasa)', 2018, 132, 4.245, 1.136, 0.204, 0.312, 0.052, 0.197, 2.327)
('Costa Rica', 2015, 12, 7.226, 1.23788, 0.86027, 0.63376, 0.10583, 0.25497, 3.17728)
('Costa Rica', 2016, 14, 7.087, 1.02152, 0.76146, 0.55225, 0.10547, 0.22553, 3.35168)
('Costa Rica', 2017, 12, 7.079, 1.4164, 0.759509, 0.580132, 0.100107, 0.214613, 2.89864)
('Costa Rica', 2018, 13, 7.072, 1.459, 0.817, 0.632, 0.101, 0.143, 3.011)
('Croatia', 2015, 62, 5.759, 0.79624, 0.78805, 0.25883, 0.0243, 0.05444, 2.75414)
('Croatia', 2016, 74, 5.488, 0.60809, 0.70524, 0.23907, 0.04002, 0.18434, 2.52462)
('Croatia', 2017, 77, 5.293, 0.967983, 0.701289, 0.255772, 0.0431031, 0.248003, 1.85449)
('Croatia', 2018, 82, 5.321, 1.161, 0.737, 0.38, 0.039, 0.12, 1.808)
('Cyprus', 2015, 67, 5.689, 0.89318, 0.92356, 0.40672, 0.06146, 0.30638, 1.88931)
('Cyprus', 2016, 69, 5.546, 0.70697, 0.8488, 0.29507, 0.05228, 0.27906, 2.04497)
('Cyprus', 2017, 65, 5.621, 1.13136, 0.844715, 0.355112, 0.041238, 0.271254, 1.62125)
('Cyprus', 2018, 61, 5.762, 1.191, 0.909, 0.423, 0.035, 0.202, 1.808)
('Czech Republic', 2015, 31, 6.505, 1.20643, 0.84483, 0.46364, 0.02652, 0.10686, 2.67782)
('Czech Republic', 2016, 27, 6.596, 1.00793, 0.76376, 0.41418, 0.03986, 0.09929, 2.96211)
('Czech Republic', 2017, 23, 6.609, 1.43389, 0.754444, 0.490946, 0.0368729, 0.0881068, 2.45186)
('Czech Republic', 2018, 21, 6.711, 1.489, 0.854, 0.543, 0.034, 0.064, 2.528)
('Denmark', 2015, 3, 7.527, 1.36058, 0.87464, 0.64938, 0.48357, 0.34139, 2.49204)
('Denmark', 2016, 1, 7.526, 1.16374, 0.79504, 0.57941, 0.44453, 0.36171, 2.73939)
('Denmark', 2017, 2, 7.522, 1.55112, 0.792566, 0.626007, 0.40077, 0.35528, 2.31371)
('Denmark', 2018, 3, 7.555, 1.59, 0.868, 0.683, 0.408, 0.284, 2.779)
('Djibouti', 2015, 126, 4.369, 0.59207, 0.36291, 0.46074, 0.28105, 0.18093, 2.05125)
('Dominican Republic', 2015, 98, 4.885, 1.17202, 0.66825, 0.57672, 0.14234, 0.21684, 1.21305)
('Dominican Republic', 2016, 89, 5.155, 0.99496, 0.57669, 0.52259, 0.12372, 0.21286, 1.69626)
('Dominican Republic', 2017, 86, 5.23, 1.40242, 0.574874, 0.55259, 0.113945, 0.186968, 1.31947)
('Dominican Republic', 2018, 83, 5.302, 1.441, 0.614, 0.578, 0.106, 0.12, 1.567)
('Ecuador', 2015, 48, 5.975, 0.99903, 0.79075, 0.48574, 0.1809, 0.11541, 2.53942)
('Ecuador', 2016, 51, 5.976, 0.85974, 0.68613, 0.4027, 0.18037, 0.10074, 2.77366)
('Ecuador', 2017, 44, 6.008, 1.28617, 0.685636, 0.455198, 0.140135, 0.150112, 2.29035)
('Ecuador', 2018, 48, 5.973, 1.33, 0.736, 0.556, 0.12, 0.114, 2.348)
('Egypt', 2015, 135, 4.194, 0.747, 0.61712, 0.17288, 0.06324, 0.11291, 1.59927)
('Egypt', 2016, 120, 4.362, 0.49813, 0.52116, 0.18847, 0.10393, 0.12706, 1.96895)
('Egypt', 2017, 104, 4.735, 0.997471, 0.520187, 0.28211, 0.114381, 0.128631, 1.70216)
('Egypt', 2018, 122, 4.419, 1.025, 0.553, 0.312, 0.107, 0.092, 1.552)
('El Salvador', 2015, 42, 6.13, 1.02507, 0.67737, 0.4035, 0.11776, 0.10692, 3.035)
('El Salvador', 2016, 46, 6.068, 0.80975, 0.596, 0.37269, 0.10613, 0.08877, 3.22134)
('El Salvador', 2017, 45, 6.003, 1.18213, 0.596019, 0.432453, 0.089981, 0.078258, 2.71459)
('El Salvador', 2018, 40, 6.167, 1.231, 0.639, 0.461, 0.082, 0.065, 2.965)
('Estonia', 2015, 73, 5.429, 1.22791, 0.77361, 0.44888, 0.15184, 0.0868, 1.58782)
('Estonia', 2016, 72, 5.517, 1.05163, 0.68098, 0.41511, 0.18519, 0.08423, 1.81985)
('Estonia', 2017, 66, 5.611, 1.47667, 0.695168, 0.479131, 0.183249, 0.0988908, 1.35751)
('Estonia', 2018, 63, 5.739, 1.532, 0.737, 0.553, 0.174, 0.086, 1.631)
('Ethiopia', 2015, 122, 4.512, 0.60406, 0.44055, 0.4345, 0.15048, 0.24325, 2.44876)
('Ethiopia', 2016, 115, 4.508, 0.37932, 0.34578, 0.36703, 0.1717, 0.29522, 2.65614)
('Ethiopia', 2017, 119, 4.46, 0.864669, 0.35341, 0.408843, 0.165456, 0.312651, 2.01574)
('Ethiopia', 2018, 127, 4.35, 0.95, 0.391, 0.452, 0.146, 0.22, 2.029)
('Finland', 2015, 6, 7.406, 1.31826, 0.88911, 0.64169, 0.41372, 0.23351, 2.61955)
('Finland', 2016, 5, 7.413, 1.13464, 0.81091, 0.57104, 0.41004, 0.25492, 2.82596)
('Finland', 2017, 5, 7.469, 1.54025, 0.809158, 0.617951, 0.382612, 0.245483, 2.43018)
('Finland', 2018, 1, 7.632, 1.592, 0.874, 0.681, 0.393, 0.192, 2.988)
('France', 2015, 29, 6.575, 1.26038, 0.94579, 0.55011, 0.20646, 0.12332, 2.21126)
('France', 2016, 32, 6.478, 1.00508, 0.83795, 0.46562, 0.17808, 0.1216, 2.4744)
('France', 2017, 31, 6.442, 1.38778, 0.844466, 0.470222, 0.172502, 0.129762, 2.00595)
('France', 2018, 23, 6.489, 1.466, 0.908, 0.52, 0.176, 0.098, 2.204)
('Gabon', 2015, 143, 3.896, 0.90528, 0.43372, 0.31914, 0.11091, 0.06822, 0.99895)
('Gabon', 2016, 134, 4.121, 0.72368, 0.3494, 0.28098, 0.09314, 0.06244, 1.45332)
('Gabon', 2017, 118, 4.465, 1.15562, 0.356579, 0.312329, 0.0760468, 0.0437854, 1.32292)
('Gabon', 2018, 103, 4.758, 1.164, 0.404, 0.356, 0.052, 0.032, 1.766)
('Georgia', 2015, 130, 4.297, 0.38562, 0.72926, 0.40577, 0.38331, 0.05547, 1.59541)
('Georgia', 2016, 126, 4.252, 0.19249, 0.64035, 0.32461, 0.3188, 0.06786, 1.87031)
('Georgia', 2017, 125, 4.286, 0.570615, 0.649547, 0.30941, 0.251667, 0.0540088, 1.50014)
('Georgia', 2018, 128, 4.34, 0.592, 0.643, 0.375, 0.215, 0.038, 1.839)
('Germany', 2015, 26, 6.75, 1.29937, 0.89186, 0.61477, 0.21843, 0.28214, 2.11569)
('Germany', 2016, 16, 6.994, 1.09774, 0.81487, 0.53466, 0.28551, 0.30452, 2.50931)
('Germany', 2017, 16, 6.951, 1.47252, 0.798951, 0.562511, 0.276732, 0.336269, 2.01577)
('Germany', 2018, 15, 6.965, 1.474, 0.861, 0.586, 0.28, 0.273, 2.431)
('Ghana', 2015, 114, 4.633, 0.67954, 0.40132, 0.42342, 0.04355, 0.23087, 2.30919)
('Ghana', 2016, 124, 4.276, 0.49353, 0.29681, 0.40973, 0.0326, 0.21203, 2.2002)
('Ghana', 2017, 131, 4.12, 0.873665, 0.295638, 0.423026, 0.0253364, 0.256924, 1.57787)
('Ghana', 2018, 108, 4.657, 0.896, 0.337, 0.499, 0.029, 0.212, 2.121)
('Greece', 2015, 102, 4.857, 0.92933, 0.88213, 0.07699, 0.01397, 0.0, 1.80101)
('Greece', 2016, 99, 5.033, 0.75473, 0.80029, 0.05822, 0.04127, 0.0, 2.12944)
('Greece', 2017, 87, 5.227, 1.23941, 0.810199, 0.0957313, 0.0432898, 0.0, 1.74922)
('Greece', 2018, 79, 5.358, 1.202, 0.879, 0.131, 0.044, 0.0, 1.992)
('Guatemala', 2015, 43, 6.123, 1.04356, 0.64425, 0.57733, 0.09472, 0.27489, 2.74255)
('Guatemala', 2016, 39, 6.324, 0.87119, 0.54039, 0.50379, 0.08701, 0.28808, 3.19863)
('Guatemala', 2017, 29, 6.454, 1.25559, 0.54024, 0.531311, 0.0772233, 0.283488, 2.89389)
('Guatemala', 2018, 30, 6.382, 1.268, 0.608, 0.604, 0.071, 0.179, 2.942)
('Guinea', 2015, 150, 3.656, 0.46475, 0.24009, 0.37725, 0.12139, 0.28657, 1.99172)
('Guinea', 2016, 151, 3.607, 0.3109, 0.18829, 0.30953, 0.1192, 0.29914, 2.15604)
('Guinea', 2017, 149, 3.507, 0.791245, 0.194129, 0.348588, 0.110938, 0.264815, 1.55231)
('Guinea', 2018, 140, 3.964, 0.792, 0.211, 0.394, 0.094, 0.185, 2.038)
('Haiti', 2015, 119, 4.518, 0.74302, 0.38847, 0.24425, 0.17175, 0.46187, 2.24173)
('Haiti', 2016, 136, 4.028, 0.29561, 0.27494, 0.12072, 0.14476, 0.47958, 2.37116)
('Haiti', 2017, 145, 3.603, 0.64045, 0.277321, 0.0303699, 0.0998721, 0.489204, 1.69717)
('Haiti', 2018, 148, 3.582, 0.714, 0.289, 0.025, 0.104, 0.392, 1.847)
('Honduras', 2015, 105, 4.788, 0.95348, 0.6951, 0.40148, 0.06825, 0.23027, 1.84408)
('Honduras', 2016, 104, 4.871, 0.75596, 0.58383, 0.26755, 0.06906, 0.2044, 2.29551)
('Honduras', 2017, 91, 5.181, 1.14394, 0.582569, 0.34808, 0.0733455, 0.236189, 2.06581)
('Honduras', 2018, 72, 5.504, 1.205, 0.622, 0.459, 0.074, 0.197, 2.401)
('Hong Kong', 2015, 72, 5.474, 1.05818, 1.01328, 0.59608, 0.37124, 0.39478, 0.65429)
('Hong Kong', 2016, 75, 5.458, 0.87021, 0.95277, 0.48079, 0.31647, 0.40097, 0.92614)
('Hong Kong', 2018, 76, 5.43, 1.29, 1.03, 0.524, 0.291, 0.246, 0.935)
('Hong Kong S.A.R., China', 2017, 71, 5.472, 1.26279, 0.943062, 0.490969, 0.293934, 0.374466, 0.554633)
('Hungary', 2015, 104, 4.8, 1.20215, 0.75905, 0.32112, 0.02758, 0.128, 1.24074)
('Hungary', 2016, 91, 5.145, 0.93164, 0.67608, 0.1977, 0.04472, 0.099, 1.95473)
('Hungary', 2017, 75, 5.324, 1.34313, 0.687763, 0.175864, 0.0366369, 0.0784017, 1.71646)
('Hungary', 2018, 69, 5.62, 1.401, 0.732, 0.259, 0.022, 0.061, 1.996)
('Iceland', 2015, 2, 7.561, 1.40223, 0.94784, 0.62877, 0.14145, 0.4363, 2.70201)
('Iceland', 2016, 3, 7.501, 1.18326, 0.86733, 0.56624, 0.14975, 0.47678, 2.83137)
('Iceland', 2017, 3, 7.504, 1.61057, 0.833552, 0.627163, 0.153527, 0.47554, 2.32272)
('Iceland', 2018, 4, 7.495, 1.644, 0.914, 0.677, 0.138, 0.353, 2.564)
('India', 2015, 117, 4.565, 0.38174, 0.51529, 0.39786, 0.08492, 0.26475, 2.27513)
('India', 2016, 118, 4.404, 0.29247, 0.45091, 0.40285, 0.08722, 0.25028, 2.18032)
('India', 2017, 122, 4.315, 0.754373, 0.455428, 0.469987, 0.0922269, 0.231538, 1.51912)
('India', 2018, 133, 4.19, 0.747, 0.485, 0.539, 0.093, 0.172, 1.526)
('Indonesia', 2015, 74, 5.399, 1.08708, 0.63793, 0.46611, 0.0, 0.51535, 1.86399)
('Indonesia', 2016, 79, 5.314, 0.87625, 0.49374, 0.39237, 0.00322, 0.56521, 2.03171)
('Indonesia', 2017, 81, 5.262, 1.27444, 0.492346, 0.443323, 0.0153171, 0.611705, 1.42948)
('Indonesia', 2018, 96, 5.093, 1.215, 0.522, 0.538, 0.018, 0.484, 1.435)
('Iran', 2015, 110, 4.686, 0.54447, 0.69805, 0.30033, 0.05863, 0.38086, 1.6944)
('Iran', 2016, 105, 4.813, 0.38857, 0.64232, 0.22544, 0.0557, 0.38538, 1.99817)